package com.example.EcoConsciousApp.service;

import com.example.EcoConsciousApp.entity.VendorProductScrapsPurchaseDetail;
import com.example.EcoConsciousApp.entity.VendorUsableProductRegistrationDetail;

public interface VendorUsableProductRegistrationDetailService {
    VendorUsableProductRegistrationDetail saveRegistrationDetail(VendorUsableProductRegistrationDetail registrationDetail);
}
